version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: resume-parser-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      - ./resume-parser/build:/app/frontend/build
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
    command: >
      sh -c "python -m flask run --host=0.0.0.0 --port=8000"
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend-builder
    container_name: resume-parser-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./resume-parser:/app/frontend
      - /app/frontend/node_modules
    working_dir: /app/frontend
    env_file:
      - .env.docker
    command: sh -c "npm start"
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
